name: links

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "17 5 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --accept 200,204,403,429 './README.md' './llms.txt'
          fail: true
